# This file was generated by the {rix} R package v0.17.2 on 2025-11-13
# with following call:
# >rix(date = "2025-09-09",
#  > r_pkgs = c("languageserver",
#  > "rix",
#  > "here",
#  > "pacman",
#  > "data.table",
#  > "dplyr",
#  > "ggplot2",
#  > "fixest",
#  > "texreg",
#  > "kableExtra",
#  > "broom",
#  > "glue",
#  > "modelsummary",
#  > "haven"),
#  > system_pkgs = NULL,
#  > git_pkgs = NULL,
#  > ide = "none",
#  > project_path = path_default_nix,
#  > overwrite = TRUE,
#  > print = TRUE,
#  > r_ver = "4.5.1")
# It uses the `rstats-on-nix` fork of `nixpkgs` which provides improved
# compatibility with older R versions and R packages for Linux/WSL and
# Apple Silicon computers.
# Report any issues to https://github.com/ropensci/rix
let
 pkgs = import (fetchTarball "https://github.com/rstats-on-nix/nixpkgs/archive/2025-09-09.tar.gz") {};
 
  rpkgs = builtins.attrValues {
    inherit (pkgs.rPackages) 
      broom
      data_table
      dplyr
      fixest
      ggplot2
      glue
      haven
      here
      kableExtra
      languageserver
      modelsummary
      pacman
      rix
      texreg;
  };
      
  system_packages = builtins.attrValues {
    inherit (pkgs) 
      glibcLocales
      nix
      R;
  };
  
  shell = pkgs.mkShell {
    LOCALE_ARCHIVE = if pkgs.system == "x86_64-linux" then "${pkgs.glibcLocales}/lib/locale/locale-archive" else "";
    LANG = "en_US.UTF-8";
    LC_ALL = "en_US.UTF-8";
    LC_TIME = "en_US.UTF-8";
    LC_MONETARY = "en_US.UTF-8";
    LC_PAPER = "en_US.UTF-8";
    LC_MEASUREMENT = "en_US.UTF-8";
    
    buildInputs = [ rpkgs system_packages ];
    
  }; 
in
  {
    inherit pkgs shell;
  }
